#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO	0
#define ID_TEX_ENEMIES	10
#define ID_TEX_ITEMS	21
#define ID_TEX_TILESET	22
#define ID_TEX_HUD		23
#define	ID_TEX_MISC4	24

//object type ids: 0 -> 50
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5

#define OBJECT_TYPE_CLOUD	6
#define OBJECT_TYPE_BIGGRASS 7
#define OBJECT_TYPE_SMALLGRASS 8
#define OBJECT_TYPE_MYSBOX	9
#define OBJECT_TYPE_BOXES	10
#define OBJECT_TYPE_PIPE	11
#define OBJECT_TYPE_HUD		12

#define OBJECT_TYPE_PORTAL	50

// mario id: 10000 -> 19999
#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

// 50 first values is for sprite id, 50 second values is for animation id
// goomba id: 30000 -> 30099
#define ID_SPRITE_GOOMBA 30000

#define ID_ANI_GOOMBA_WALKING 30050
#define ID_SPRITE_GOOMBA_WALK_1 (ID_SPRITE_GOOMBA + 1)
#define ID_SPRITE_GOOMBA_WALK_2 (ID_SPRITE_GOOMBA + 2)

#define ID_ANI_GOOMBA_DIE 30051
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 3)

// brick id: 30100 -> 30199
#define ID_ANI_BRICK 30150
#define ID_SPRITE_BRICK 30100

// coin id: 30200 -> 30299
#define ID_SPRITE_COIN	30200

#define ID_ANI_SHOWED_COIN 30250
#define ID_SPRITE_SHOWED_COIN_1		(ID_SPRITE_COIN + 1)
#define ID_SPRITE_SHOWED_COIN_2		(ID_SPRITE_COIN + 2)
#define ID_SPRITE_SHOWED_COIN_3		(ID_SPRITE_COIN + 3)
#define ID_SPRITE_SHOWED_COIN_4		(ID_SPRITE_COIN + 4)
#define ID_SPRITE_SHOWED_COIN_5		(ID_SPRITE_COIN + 5)

#define ID_ANI_HIDDEN_COIN 30251
#define ID_SPRITE_HIDDEN_COIN_1		(ID_SPRITE_COIN + 6)
#define ID_SPRITE_HIDDEN_COIN_2		(ID_SPRITE_COIN + 7)
#define ID_SPRITE_HIDDEN_COIN_3		(ID_SPRITE_COIN + 8)

// cloud id: 30300 -> 30399
#define ID_SPRITE_CLOUD	30300

#define ID_ANI_CLOUD 30350
#define ID_SPRITE_CLOUD_TOP_LEFT		(ID_SPRITE_CLOUD + 1)
#define ID_SPRITE_CLOUD_TOP_MIDDLE		(ID_SPRITE_CLOUD + 2)
#define ID_SPRITE_CLOUD_TOP_RIGHT		(ID_SPRITE_CLOUD + 3)
#define ID_SPRITE_CLOUD_BOTTOM_LEFT		(ID_SPRITE_CLOUD + 4)
#define ID_SPRITE_CLOUD_BOTTOM_MIDDLE	(ID_SPRITE_CLOUD + 5)
#define ID_SPRITE_CLOUD_BOTTOM_RIGHT	(ID_SPRITE_CLOUD + 6)

// ground id: 30400 -> 30499
#define ID_SPRITE_GROUND 30400

#define ID_ANI_TOP_GROUND 30450
#define ID_SPRITE_GROUND_TOP_LEFT	(ID_SPRITE_GROUND + 1)
#define ID_SPRITE_GROUND_TOP_MIDDLE (ID_SPRITE_GROUND + 2)
#define ID_SPRITE_GROUND_TOP_RIGHT	(ID_SPRITE_GROUND + 3)

#define ID_ANI_BOT_GROUND 30451
#define ID_SPRITE_GROUND_BOT_LEFT	(ID_SPRITE_GROUND + 4)
#define ID_SPRITE_GROUND_BOT_MIDDLE	(ID_SPRITE_GROUND + 5)
#define ID_SPRITE_GROUND_BOT_RIGHT	(ID_SPRITE_GROUND + 6)

// big grass id: 30500 -> 30599

#define	ID_SPRITE_BIGGRASS	30500

#define ID_ANI_BIGGRASS 30550
#define	ID_SPRITE_BIGGRASS_TOP_LEFT			(ID_SPRITE_BIGGRASS + 1) 
#define	ID_SPRITE_BIGGRASS_TOP_RIGHT		(ID_SPRITE_BIGGRASS + 2)
#define	ID_SPRITE_BIGGRASS_BOTTOM_LEFT		(ID_SPRITE_BIGGRASS + 3)
#define	ID_SPRITE_BIGGRASS_BOTTOM_RIGHT		(ID_SPRITE_BIGGRASS + 4)
#define	ID_SPRITE_BIGGRASS_LEFT_FSQUARE		(ID_SPRITE_BIGGRASS + 5)
#define	ID_SPRITE_BIGGRASS_RIGHT_FSQUARE	(ID_SPRITE_BIGGRASS + 6)
#define	ID_SPRITE_BIGGRASS_SINGLE			(ID_SPRITE_BIGGRASS + 7)

// small grass id: 30600 -> 30699
#define ID_ANI_SMALLGRASS		30650
#define ID_SPRITE_SMALLGRASS	30600

// mysbox id: 30700 -> 30799
#define ID_SPRITE_MYSBOX	30700

#define ID_ANI_MYSBOX_CARRY_OBJECT 30750
#define ID_SPRITE_MYSBOX_1	(ID_SPRITE_MYSBOX + 1)
#define ID_SPRITE_MYSBOX_2	(ID_SPRITE_MYSBOX + 2)
#define ID_SPRITE_MYSBOX_3	(ID_SPRITE_MYSBOX + 3)
#define ID_SPRITE_MYSBOX_4	(ID_SPRITE_MYSBOX + 4)

#define ID_ANI_MYSBOX_EMPTY 30751
#define ID_SPRITE_MYSBOX_5	(ID_SPRITE_MYSBOX + 5)

// box id: 30800 -> 30899
#define ID_SPRITE_BOXES	30800

#define ID_ANI_PINK_BOX	30850
#define	ID_SPRITE_PINK_BOX_TOP_LEFT			(ID_SPRITE_BOXES + 1)
#define	ID_SPRITE_PINK_BOX_TOP_MIDDLE		(ID_SPRITE_BOXES + 2)
#define	ID_SPRITE_PINK_BOX_TOP_RIGHT		(ID_SPRITE_BOXES + 3)
#define	ID_SPRITE_PINK_BOX_MIDDLE_LEFT		(ID_SPRITE_BOXES + 4)
#define	ID_SPRITE_PINK_BOX_CENTER			(ID_SPRITE_BOXES + 5)
#define	ID_SPRITE_PINK_BOX_MIDDLE_RIGHT		(ID_SPRITE_BOXES + 6)
#define	ID_SPRITE_PINK_BOX_BOTTOM_LEFT		(ID_SPRITE_BOXES + 7)
#define	ID_SPRITE_PINK_BOX_BOTTOM_MIDDLE	(ID_SPRITE_BOXES + 8)
#define	ID_SPRITE_PINK_BOX_BOTTOM_RIGHT		(ID_SPRITE_BOXES + 9)


#define ID_ANI_BLUE_BOX	30851
#define	ID_SPRITE_BLUE_BOX_TOP_LEFT			(ID_SPRITE_BOXES + 11)
#define	ID_SPRITE_BLUE_BOX_TOP_MIDDLE		(ID_SPRITE_BOXES + 12)
#define	ID_SPRITE_PINK_BOX_TOP_RIGHT		(ID_SPRITE_BOXES + 13)
#define	ID_SPRITE_BLUE_BOX_MIDDLE_LEFT		(ID_SPRITE_BOXES + 14)
#define	ID_SPRITE_BLUE_BOX_CENTER			(ID_SPRITE_BOXES + 15)
#define	ID_SPRITE_BLUE_BOX_MIDDLE_RIGHT		(ID_SPRITE_BOXES + 16)
#define	ID_SPRITE_BLUE_BOX_BOTTOM_LEFT		(ID_SPRITE_BOXES + 17)
#define	ID_SPRITE_BLUE_BOX_BOTTOM_MIDDLE	(ID_SPRITE_BOXES + 18)
#define	ID_SPRITE_BLUE_BOX_BOTTOM_RIGHT		(ID_SPRITE_BOXES + 19)


#define ID_ANI_GREEN_BOX 30852
#define	ID_SPRITE_GREEN_BOX_TOP_LEFT		(ID_SPRITE_BOXES + 21)
#define	ID_SPRITE_GREEN_BOX_TOP_MIDDLE		(ID_SPRITE_BOXES + 22)
#define	ID_SPRITE_GREEN_BOX_TOP_RIGHT		(ID_SPRITE_BOXES + 23)
#define	ID_SPRITE_GREEN_BOX_MIDDLE_LEFT		(ID_SPRITE_BOXES + 24)
#define	ID_SPRITE_GREEN_BOX_CENTER			(ID_SPRITE_BOXES + 25)
#define	ID_SPRITE_GREEN_BOX_MIDDLE_RIGHT	(ID_SPRITE_BOXES + 26)
#define	ID_SPRITE_GREEN_BOX_BOTTOM_LEFT		(ID_SPRITE_BOXES + 27)
#define	ID_SPRITE_GREEN_BOX_BOTTOM_MIDDLE	(ID_SPRITE_BOXES + 28)
#define	ID_SPRITE_GREEN_BOX_BOTTOM_RIGHT	(ID_SPRITE_BOXES + 29)

#define ID_ANI_WHITE_BOX 30853
#define	ID_SPRITE_WHITE_BOX_TOP_LEFT		(ID_SPRITE_BOXES + 31)
#define	ID_SPRITE_WHITE_BOX_TOP_MIDDLE		(ID_SPRITE_BOXES + 32)
#define	ID_SPRITE_WHITE_BOX_TOP_RIGHT		(ID_SPRITE_BOXES + 33)
#define	ID_SPRITE_WHITE_BOX_MIDDLE_LEFT		(ID_SPRITE_BOXES + 34)
#define	ID_SPRITE_WHITE_BOX_CENTER			(ID_SPRITE_BOXES + 35)
#define	ID_SPRITE_WHITE_BOX_MIDDLE_RIGHT	(ID_SPRITE_BOXES + 36)
#define	ID_SPRITE_WHITE_BOX_BOTTOM_LEFT		(ID_SPRITE_BOXES + 37)
#define	ID_SPRITE_WHITE_BOX_BOTTOM_MIDDLE	(ID_SPRITE_BOXES + 38)
#define	ID_SPRITE_WHITE_BOX_BOTTOM_RIGHT	(ID_SPRITE_BOXES + 39)

// shadow id is used by all type of boxes
#define	ID_SPRITE_SHADOW_TOP	30840
#define	ID_SPRITE_SHADOW_REST	30841

// pipe id: 30900 -> 30999
#define ID_SPRITE_PIPE	30900

#define ID_ANI_PIPE 30950
#define ID_SPRITE_PIPE_TOP_LEFT			(ID_SPRITE_PIPE + 1)
#define ID_SPRITE_PIPE_TOP_RIGHT		(ID_SPRITE_PIPE + 2)
#define ID_SPRITE_PIPE_BOTTOM_LEFT		(ID_SPRITE_PIPE + 3)
#define ID_SPRITE_PIPE_BOTTOM_RIGHT		(ID_SPRITE_PIPE + 4)

#define ID_SPRITE_HUD	11111